source "https://rubygems.org"

gem "activesupport"
gem "guard"
gem "minitest"
gem 'mocha', '1.1.0'
gem "rake"
gem 'rspec', '3.3.0'
gem "rubocop"
gem "test-unit"

gem "minitest-reporters"
# require 'minitest/reporters'
# Minitest::Reporters.use! [Minitest::Reporters::DefaultReporter.new(color: true)]
